language: node_js
node_js:
- '6'
- '8'
- '10'
- '12'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
before_install:
- export CC="gcc-4.9" CXX="g++-4.9"
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: LSufSRMVGPxMUb0A+g2QXb7XOTaNbBcR7vP9grgOsxGCES2n4EvqxnQNSvJVw7f3EI6JqcD6tybM0dTqXiDPxSaiX6OAXgrzC30k3tF6rIOvBkPIJWTTBl88xrOxfcCRVOdmje3rWipMOL9Y1mloyGISDPpZ/yyE2OCtZq+r1tHSLovBv0AasZhUg4dp8NjAskjDTdbRQcEFsHHMosFR6qdoFsm8FfriZ65L3j/YlZpXCqNXIWduItIc8d8Rq2lHk92Ki07TqsWxmKa12eQ95kSrmDuB8QyIPocMohLSh3yVlGQ+By0TV2iGBPMDUjjDdQp8xpVuId4MNS/2YwKmnm/XTTtSklPkfmr1t99iwBmh1ElBBpm/1FNb6j20ZlXYPzkIcEkvg2eReR4U2OZgTiwKIfTYHWo93n88Bkq5eZKqRK9LKZRcE2WycTQrfJ0IZDe/afw3iyY9z4zPQz6/W7AdPsjFuyGiYxIwTHAO7vsAMms25zG7q+Pb8zqoQt0uf1TEQWIGyLuarONltwySBjNO68CQxQZfIZLgvhjA/2CFddQ4+BSgQ+GOjFwk32XZs7+ykkOpwcs0sY42pP6BcKEih8kPYAry5U/XKUC1O6XFxcSmPAW3nZdUIG4iTxwoImIQQWLfVgbLbdVeX/Ln61ReVuLaDT4oTnrM4QSGt6U=
  on:
    repo: kuzzleio/dumpme
    branch: master
